site_name: "Notebook"
site_url: https://campusrover.github.io/labnotebook2/
plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md

theme:
  name: material
  features:
    - content.action.edit
    - navigation.tabs
    - toc.integrate
    - header.autohide
  icon:
    logo: material/robot
  palette:
    primary: teal
    accent: purple

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - mystyle.css
